Add support for type checking with mypy plugins
hauntsaninja/mypy_primer pull request #121
Opened 2024-04-19 20:26 UTC by flaeppe

I'm not totally sure if this approach always works or if there's stuff that I'm missing, but it seems to work. I'll try to explain myself here.

The change utilises `pip`'s `--target`([docs](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-t)) argument to point out where to install a project's additional dependencies, passed in via `pip_cmd`. This replaces the virtual env creation for each project, since that shouldn't be necessary (I think?).

In addition to what's mentioned above we start setting the `PYTHONPATH` env variable([docs](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH)), to point out an additional search path for module files, namely the directory with the additional dependencies.

That should allow discovery of project dependencies while keeping the installed mypy versions independent and reusable.

- Closes #8 
- Closes #102 

---

All this _isn't_ included, but I was thinking that it _should_ be possible to use `pip install --target` for both mypy installations as well, instead of a virtual env. That leads to having 1 python/pip executable, 1 directory for `new_mypy`, 1 directory for `old_mypy` and then all project dependency installations. Although I'm unsure what `--python-executable=` does and if it could be affected.

Essentially what'll happen with the above changes is that we'll have a directory structure like e.g.

```bash
repo-dir/
├── new_mypy
│   └── bin
│       └── mypy
├── old_mypy
│   └── bin
│       └── mypy
├── projects
│   ├── A
│   └── B
└── python
    └── bin
        └── python
```

We run mypy with something corresponding to

```
PYTHONPATH="repo-dir/new_mypy:repo-dir/projects/A" repo-dir/new_mypy/bin/mypy --python-executable=repo-dir/python/bin/python ...
PYTHONPATH="repo-dir/old_mypy:repo-dir/projects/A" repo-dir/old_mypy/bin/mypy --python-executable=repo-dir/python/bin/python ...
```

2024-04-19 20:29 UTC, flaeppe commented on mypy_primer/model.py
> +        env["PYTHONPATH"] = os.pathsep.join(pythonpath)
Forgot to prepend `repo-dir/{new|old}_mypy/venv/lib/python3.XX/site-packages` here, slightly fiddly to get hold of the path though.

Need it in case `mypy` would be installed by any additional deps we've installed, we want precedence on old/new mypy

2024-04-19 20:45 UTC, flaeppe commented on mypy_primer/model.py
> +            python_exe = ctx.get().venv_dir / BIN_DIR / "python"
Hm, perhaps we shouldn't change the `--python-executable=` binary in this PR.

I'm not at all sure what could happen if we do/don't but it seems to work as intended without change, so we could keep it unchanged

2024-04-19 20:47 UTC, flaeppe commented on mypy_primer/model.py
> +            python_exe = ctx.get().venv_dir / BIN_DIR / "python"
Oh, nvm, I was confusing this with thinking it was set to the python binary within the old/new mypy directories. `self.venv_dir / BIN_DIR / "python"` doesn't exist any longer since we don't have a virtual env for each project.

2024-04-19 21:55 UTC, flaeppe commented on mypy_primer/model.py
> +        env["PYTHONPATH"] = os.pathsep.join(pythonpath)
Fixed in 04e79e8dfb29d786b115b175388b9bf1811307fc

2024-04-20 06:32 UTC, flaeppe commented on mypy_primer/model.py
> +            )
Hm since the venv was previously created with `clear=True` it might be that we want to install with either `--force-reinstall` or `--ignore-installed`

2024-04-28 22:08 UTC, hauntsaninja requested changes
Thanks for the PR!

I don't quite understand what the new global env is for. Other than that, I think this PR mostly does the right thing: we should continue to setup a) a venv for mypy itself, b) project specific venvs. And then use `PYTHONPATH` (or other) shenanigans so that mypy can import from the project specific venv. We should also add an assert that some version of mypy itself isn't in the project specific venv, otherwise things will get confusing.

2024-04-29 05:47 UTC, flaeppe commented
Thanks for the review, I'm gonna try to move back to using project specific venvs, see if I can get it to work.

The global env was added to have a python/pip binary to reach to when I removed the project specific venvs.

I'll see if I can get a reasonable assert in there too, perhaps just something naive like looking for `bin/mypy` in a project specific venv is enough.

2024-04-29 08:03 UTC, flaeppe commented
I've updated to align with your suggestions. Let me know if there's anything else I've missed or should update.

Though I can't say I follow why each project needs its own environment. I was thinking it would be preferable to have a virtualenv for each mypy installation and then do a "distributed" install for each project (`pip install --target`) and via `PYTHONPATH=` "mount" in the relevant dependencies for each project run. But I might definitely miss something.

2024-07-01 02:12 UTC, closed without merging

2024-07-01 02:14 UTC, hauntsaninja commented
Thanks again for the PR, sorry that I lost track of it!
This developed a few merge conflicts, I fixed in 83721d5. I also altered the approach slightly, I use a `.pth` file to *append* to sys.path, so that project venv will never cause conflicts with mypy and its dependencies.