Raise exception if selector matches nothing
hauntsaninja/mypy_primer pull request #19
Opened 2021-09-03 02:57 UTC by nipunn1313

I had issues w/ typos in my selector and ideally it would catch those
early and fails fast. This achieves that.

2021-09-03 03:11 UTC, nipunn1313 commented on test.sh
> +flake8 --max-line-length 100 --ignore E203,W503 $(git ls-files | grep "py$")
I had a .venv and it was hanging here because it would try to flake8 the entire venv.
Rolled in this fix here.

2021-09-05 23:53 UTC, hauntsaninja requested changes
Thanks, seems like a helpful change! :-)

2021-09-05 23:53 UTC, hauntsaninja commented on mypy_primer.py
> +def select_projects() -> List[Project]:
The type annotation change here isn't correct, since we'll still return an iterator. (I'd be fine with actually returning a list too, if that's better for some reason)

2021-09-05 23:55 UTC, hauntsaninja commented on mypy_primer.py
> +def select_projects() -> List[Project]:
(I was surprised why mypy didn't complain, it's because we now just ignore project_iter)

2021-09-06 22:46 UTC, nipunn1313 commented on mypy_primer.py
> +def select_projects() -> List[Project]:
oh wow - this is actually messed up badly. It won't work if `-k` isn't provided. Unfortunate that it wasn't caught by mypy. Will manually test with and without `-k` and fix.

2021-09-06 22:50 UTC, nipunn1313 commented on mypy_primer.py
> +def select_projects() -> List[Project]:
Updated!

2021-09-06 22:59 UTC, merged

2021-09-06 22:59 UTC, hauntsaninja commented
Thanks, looks fixed!